### ISSUE TITLE
llvm: clang installed from linuxbrew is not able to link binary executable

### ISSUE THREAD

**Issue by Liam0205** [Homebrew/linuxbrew-core#22034] opened 2021-01-06 13:34 UTC
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<details>
  <summary>Command output of brew config and brew doctor</summary>
  <pre>
$ brew config
HOMEBREW_VERSION: 2.7.1-143-gb678af3
ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HEAD: b678af3fa33a6faaf8645ca8c1064e58fc2458b5
Last commit: 22 hours ago
Core tap ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/linuxbrew-core.git
Core tap HEAD: 661d378bc98b0e950434608f904f40164d50c4de
Core tap last commit: 14 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/linuxbrew-core.git
HOMEBREW_EDITOR: vim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_MAKE_JOBS: 32
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit broadwell
Clang: 11.0 build (parse error)
Git: 2.30.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.74.0 => /home/linuxbrew/.linuxbrew/opt/curl/bin/curl
Kernel: Linux 4.18.0-2.3.4.kwai.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.3.1611 (Core) 
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
/usr/bin/ruby: N/A
glibc: 2.23
gcc: 5.5.0_7
xorg: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/evdns.h
  /usr/local/include/event.h
  /usr/local/include/event2/buffer.h
  /usr/local/include/event2/buffer_compat.h
  /usr/local/include/event2/bufferevent.h
  /usr/local/include/event2/bufferevent_compat.h
  /usr/local/include/event2/bufferevent_ssl.h
  /usr/local/include/event2/bufferevent_struct.h
  /usr/local/include/event2/dns.h
  /usr/local/include/event2/dns_compat.h
  /usr/local/include/event2/dns_struct.h
  /usr/local/include/event2/event-config.h
  /usr/local/include/event2/event.h
  /usr/local/include/event2/event_compat.h
  /usr/local/include/event2/event_struct.h
  /usr/local/include/event2/http.h
  /usr/local/include/event2/http_compat.h
  /usr/local/include/event2/http_struct.h
  /usr/local/include/event2/keyvalq_struct.h
  /usr/local/include/event2/listener.h
  /usr/local/include/event2/rpc.h
  /usr/local/include/event2/rpc_compat.h
  /usr/local/include/event2/rpc_struct.h
  /usr/local/include/event2/tag.h
  /usr/local/include/event2/tag_compat.h
  /usr/local/include/event2/thread.h
  /usr/local/include/event2/util.h
  /usr/local/include/event2/visibility.h
  /usr/local/include/evhttp.h
  /usr/local/include/evrpc.h
  /usr/local/include/evutil.h
  /usr/local/include/mpi-ext.h
  /usr/local/include/mpi.h
  /usr/local/include/mpi_portable_platform.h
  /usr/local/include/mpif-common.h
  /usr/local/include/mpif-config.h
  /usr/local/include/mpif-mpi-io.h
  /usr/local/include/mpif.h
  /usr/local/include/openmpi/ompi/mpi/cxx/comm.h
  /usr/local/include/openmpi/ompi/mpi/cxx/comm_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/constants.h
  /usr/local/include/openmpi/ompi/mpi/cxx/datatype.h
  /usr/local/include/openmpi/ompi/mpi/cxx/datatype_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/errhandler.h
  /usr/local/include/openmpi/ompi/mpi/cxx/errhandler_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/exception.h
  /usr/local/include/openmpi/ompi/mpi/cxx/file.h
  /usr/local/include/openmpi/ompi/mpi/cxx/file_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/functions.h
  /usr/local/include/openmpi/ompi/mpi/cxx/functions_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/group.h
  /usr/local/include/openmpi/ompi/mpi/cxx/group_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/info.h
  /usr/local/include/openmpi/ompi/mpi/cxx/info_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/intercomm.h
  /usr/local/include/openmpi/ompi/mpi/cxx/intercomm_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/intracomm.h
  /usr/local/include/openmpi/ompi/mpi/cxx/intracomm_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/mpicxx.h
  /usr/local/include/openmpi/ompi/mpi/cxx/op.h
  /usr/local/include/openmpi/ompi/mpi/cxx/op_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/request.h
  /usr/local/include/openmpi/ompi/mpi/cxx/request_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/status.h
  /usr/local/include/openmpi/ompi/mpi/cxx/status_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/topology.h
  /usr/local/include/openmpi/ompi/mpi/cxx/topology_inln.h
  /usr/local/include/openmpi/ompi/mpi/cxx/win.h
  /usr/local/include/openmpi/ompi/mpi/cxx/win_inln.h
  /usr/local/include/vampirtrace/OTF_CopyHandler.h
  /usr/local/include/vampirtrace/OTF_Definitions.h
  /usr/local/include/vampirtrace/OTF_Errno.h
  /usr/local/include/vampirtrace/OTF_File.h
  /usr/local/include/vampirtrace/OTF_FileManager.h
  /usr/local/include/vampirtrace/OTF_Filenames.h
  /usr/local/include/vampirtrace/OTF_HandlerArray.h
  /usr/local/include/vampirtrace/OTF_MasterControl.h
  /usr/local/include/vampirtrace/OTF_RBuffer.h
  /usr/local/include/vampirtrace/OTF_RStream.h
  /usr/local/include/vampirtrace/OTF_Reader.h
  /usr/local/include/vampirtrace/OTF_Version.h
  /usr/local/include/vampirtrace/OTF_WBuffer.h
  /usr/local/include/vampirtrace/OTF_WStream.h
  /usr/local/include/vampirtrace/OTF_Writer.h
  /usr/local/include/vampirtrace/OTF_inttypes.h
  /usr/local/include/vampirtrace/OTF_inttypes_unix.h
  /usr/local/include/vampirtrace/opari_omp.h
  /usr/local/include/vampirtrace/otf.h
  /usr/local/include/vampirtrace/pomp_lib.h
  /usr/local/include/vampirtrace/vt_libwrap.h
  /usr/local/include/vampirtrace/vt_user.h
  /usr/local/include/vampirtrace/vt_user_comment.h
  /usr/local/include/vampirtrace/vt_user_control.h
  /usr/local/include/vampirtrace/vt_user_count.h
  /usr/local/include/vampirtrace/vt_user_marker.h
  /usr/local/include/vampirtrace/vt_user_region.h
  /usr/local/include/vampirtrace/vt_wrap_pthread.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libevent.la
  /usr/local/lib/libevent_core.la
  /usr/local/lib/libevent_extra.la
  /usr/local/lib/libevent_openssl.la
  /usr/local/lib/libevent_pthreads.la
  /usr/local/lib/libmpi.la
  /usr/local/lib/libmpi_cxx.la
  /usr/local/lib/libmpi_f77.la
  /usr/local/lib/libmpi_f90.la
  /usr/local/lib/libompitrace.la
  /usr/local/lib/libvt-mpi.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/libevent.pc
  /usr/local/lib/pkgconfig/libevent_core.pc
  /usr/local/lib/pkgconfig/libevent_extra.pc
  /usr/local/lib/pkgconfig/libevent_openssl.pc
  /usr/local/lib/pkgconfig/libevent_pthreads.pc
  /usr/local/lib/pkgconfig/ompi-c.pc
  /usr/local/lib/pkgconfig/ompi-cxx.pc
  /usr/local/lib/pkgconfig/ompi-f77.pc
  /usr/local/lib/pkgconfig/ompi-f90.pc
  /usr/local/lib/pkgconfig/ompi.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libevent.a
  /usr/local/lib/libevent_core.a
  /usr/local/lib/libevent_extra.a
  /usr/local/lib/libevent_openssl.a
  /usr/local/lib/libevent_pthreads.a
  /usr/local/lib/libvt-mpi.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gcc@4.9
  gcc@5
  gcc@6
  gcc@7
  gcc@8
  gcc@9
  gcc@10
  </pre>
</details>

## What you were trying to do (and why)

I was trying to install llvm on Linux (CentOS 7) by Linuxbrew, and then build C++ project by the installed llvm (clang++).

## What happened (include command output)

`clang++` complained about linking error, as #360 reported.

<details>
  <summary>Command output</summary>
  <pre>
$ ./blade build --verbose ...
Blade: Entering directory `/home/huangchencheng/git/blade-project'
Blade(info): Loading config file "/home/huangchencheng/git/blade-project/thirdparty/blade-build/blade.conf"
Blade(info): Loading config file "/home/huangchencheng/git/blade-project/BLADE_ROOT"
Blade(info): Loading BUILD files...
Blade(info): Loading done.
Blade(info): Analyzing dependency graph...
Blade(info): Analyzing done.
Blade(info): Generating build rules...
Blade(debug): Generating build64_release/test/fibonacci.build.ninja
Blade(info): Generating done.
Blade(info): Building...
Blade(info): Adjust build jobs number(-j N) to be 8
Blade(debug): Run build command: ninja -f build64_release/build.ninja -j8 -v
[1/4] PYTHONPATH=/home/huangchencheng/git/blade-project/thirdparty/blade-build/src:$PYTHONPATH /usr/bin/python -m blade.builtin_tools scm --scm=build64_release/scm.cc --revision=4b01e5348d3943fc1a69ba32cb057d124735f113 --url=git@github.com:Liam0205/blade-project.git --profile=release --compiler="clang 11.0.0"
[2/4] export LC_ALL=C; set -o pipefail; clang++ -o build64_release/scm.cc.o -MMD -MF build64_release/scm.cc.o.d -c -fPIC -std=c++17 -pipe -fno-omit-frame-pointer -g -DNDEBUG -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -w -O2 -Ithirdparty -I. -Ibuild64_release  build64_release/scm.cc -H 2>&1 | awk 'BEGIN {stop=0} /^Multiple include guards may be useful for:/ {stop=1} !stop {if ($1 ~/^\.+$/) print $0; else print $0 > "/dev/stderr"}' > build64_release/scm.cc.o.H
[3/4] export LC_ALL=C; set -o pipefail; clang++ -o build64_release/test/fibonacci.objs/fibonacci.cc.o -MMD -MF build64_release/test/fibonacci.objs/fibonacci.cc.o.d -c -fPIC -std=c++17 -pipe -fno-omit-frame-pointer -g -DNDEBUG -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -Wall -Wall  -Ithirdparty -I. -Ibuild64_release  test/fibonacci.cc -H 2>&1 | awk 'BEGIN {stop=0} /^Multiple include guards may be useful for:/ {stop=1} !stop {if ($1 ~/^\.+$/) print $0; else print $0 > "/dev/stderr"}' > build64_release/test/fibonacci.objs/fibonacci.cc.o.H
[4/4] clang++ -o build64_release/test/fibonacci   build64_release/test/fibonacci.objs/fibonacci.cc.o build64_release/scm.cc.o
FAILED: build64_release/test/fibonacci 
clang++ -o build64_release/test/fibonacci   build64_release/test/fibonacci.objs/fibonacci.cc.o build64_release/scm.cc.o
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0/../../../libstdc++.so: undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Blade(error): Build failure.
Blade(info): Cost time 45s
Blade(error): Failure
  </pre>
</details>

<details>
  <summary>Command output, when running clang++ in verbose mode</summary>
  <pre>
$ clang++ -v -o build64_release/test/fibonacci   build64_release/test/fibonacci.objs/fibonacci.cc.o build64_release/scm.cc.o                                                                                    
clang version 11.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/linuxbrew/.linuxbrew/bin
Found candidate GCC installation: /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/linuxbrew/.linuxbrew/bin/ld" --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o build64_release/test/fibonacci /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0/crt1.o /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0/crti.o /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0/crtbegin.o -L/home/linuxbrew/.linuxbrew/Cellar/llvm/11.0.0/bin/../lib/x86_64-unknown-linux-gnu/c++ -L/home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0 -L/home/linuxbrew/.linuxbrew/Cellar/llvm/11.0.0/bin/../lib/x86_64-unknown-linux-gnu -L/lib/../lib64 -L/usr/lib/../lib64 -L/home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0/../../.. -L/home/linuxbrew/.linuxbrew/Cellar/llvm/11.0.0/bin/../lib -L/lib -L/usr/lib build64_release/test/fibonacci.objs/fibonacci.cc.o build64_release/scm.cc.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0/crtend.o /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0/crtn.o
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0/../../../libstdc++.so: undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
  </pre>
</details>

## What you expected to happen

Fix the linking error.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install llvm
pip3 install ninja
git clone git@github.com:Liam0205/blade-project.git --recursive  # this is a small template repo.
cd blade-project
ln -sf config/blade/build.clang.linuxbrew.conf build.conf  # this line ensures using llvm.
./blade build --verbose ...
```

**Comment by iMichka** [comment] 2021-01-06 14:18
The error is:
> /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0/../../../libstdc++.so: undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'

I think it's using the wrong libstdc++.so file. Not sure how to fix this.

**Comment by Liam0205** [comment] 2021-01-06 14:23
> The error is:
> 
> > /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0/../../../libstdc++.so: undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'
> 
> I think it's using the wrong libstdc++.so file. Not sure how to fix this.

This error is almost the same as the one reported in #360, which has been fixed but now emerged again. @mikeandmore and @maxim-belkin might have some clues?

**Comment by danielnachun** [comment] 2021-01-13 18:07
I actually think this is happening because when you install `ninja` with `pip3`, it is downloading some precompiled binaries which are using the dynamic linker from the system `glibc` instead of the one from the brewed `glibc`.  This creates a conflict where your compiled binary is using the system `glibc` while `libstdc++` is used the brewed `glibc`.  

Can you install ninja with Linuxbrew instead?  If not, you'll need to use `patchelf` on the binaries installed by `pip3` to make them use the brewed `glibc` instead (I can give instructions on this).  I've used this trick to make `rustup` work before.  I should write some documentation on how to deal with this because it is an inevitable problem when you mix binaries built with different versions of `glibc`.

**Comment by Liam0205** [comment] 2021-01-14 09:33
@danielnachun Thanks for your notes.

After 

```shell
pip3 uninstall ninja
brew install ninja
```

rebuilding `./blade build --verbose ...` still gives the following

```
$ ./blade build --verbose ...
Blade: Entering directory `/home/huangchencheng/git/blade-project'
Blade(info): Loading config file "/home/huangchencheng/git/blade-project/thirdparty/blade-build/blade.conf"
Blade(info): Loading config file "/home/huangchencheng/git/blade-project/BLADE_ROOT"
Blade(info): Loading BUILD files...
Blade(info): Loading done.
Blade(info): Analyzing dependency graph...
Blade(info): Analyzing done.
Blade(info): Generating build rules...
Blade(debug): Generating build64_release/test/fibonacci.build.ninja
Blade(info): Generating done.
Blade(info): Building...
Blade(info): Adjust build jobs number(-j N) to be 8
Blade(debug): Run build command: ninja -f build64_release/build.ninja -j8 -v
[1/4] PYTHONPATH=/home/huangchencheng/git/blade-project/thirdparty/blade-build/src:$PYTHONPATH /usr/bin/python -m blade.builtin_tools scm --scm=build64_release/scm.cc --revision=4b01e5348d3943fc1a69ba32cb057d124735f113 --url=git@github.com:Liam0205/blade-project.git --profile=release --compiler="clang 11.0.0"
[2/4] export LC_ALL=C; set -o pipefail; clang++ -o build64_release/scm.cc.o -MMD -MF build64_release/scm.cc.o.d -c -fPIC -std=c++17 -pipe -fno-omit-frame-pointer -g -DNDEBUG -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -w -O2 -Ithirdparty -I. -Ibuild64_release  build64_release/scm.cc -H 2>&1 | awk 'BEGIN {stop=0} /^Multiple include guards may be useful for:/ {stop=1} !stop {if ($1 ~/^\.+$/) print $0; else print $0 > "/dev/stderr"}' > build64_release/scm.cc.o.H
[3/4] export LC_ALL=C; set -o pipefail; clang++ -o build64_release/test/fibonacci.objs/fibonacci.cc.o -MMD -MF build64_release/test/fibonacci.objs/fibonacci.cc.o.d -c -fPIC -std=c++17 -pipe -fno-omit-frame-pointer -g -DNDEBUG -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -Wall -Wall  -Ithirdparty -I. -Ibuild64_release  test/fibonacci.cc -H 2>&1 | awk 'BEGIN {stop=0} /^Multiple include guards may be useful for:/ {stop=1} !stop {if ($1 ~/^\.+$/) print $0; else print $0 > "/dev/stderr"}' > build64_release/test/fibonacci.objs/fibonacci.cc.o.H
[4/4] clang++ -o build64_release/test/fibonacci   build64_release/test/fibonacci.objs/fibonacci.cc.o build64_release/scm.cc.o
FAILED: build64_release/test/fibonacci 
clang++ -o build64_release/test/fibonacci   build64_release/test/fibonacci.objs/fibonacci.cc.o build64_release/scm.cc.o
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.5.0/../../../libstdc++.so: undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Blade(error): Build failure.
Blade(info): Cost time 37s
Blade(error): Failure
```

**Comment by Liam0205** [comment] 2021-01-14 09:38
> If not, you'll need to use `patchelf` on the binaries installed by `pip3` to make them use the brewed `glibc` instead (I can give instructions on this). I've used this trick to make `rustup` work before. I should write some documentation on how to deal with this because it is an inevitable problem when you mix binaries built with different versions of `glibc`.

Well, that sounds interesting. Please let me know, if the doc published. : )

**Comment by danielnachun** [comment] 2021-01-14 21:00
It seems I was wrong about ninja being the problem, but I still think the issue is that something is forcing you to link to the system `glibc` instead of the brewed one.  

I see in your GitHub repo for this test that you have a `build.clang.linuxbrew.conf` which is supposed to add some `LDFLAGS` when linking, but it doesn't actually look like those `LDFLAGS` have even been added (I think they should be added after `clang++ -o build64_release/test/fibonacci` in line `4/4`, and there's even a suspicious blank space there).  

If you can figure how to make them be used, you should try adding `-L/home/linuxbrew/.linuxbrew/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib` to the `LDFLAGS` as this should hopefully make it use the brewed `glibc` instead of the system one.

**Comment by danielnachun** [comment] 2021-03-27 01:04
I think the root issue here may be related to this patch https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/llvm@9.rb#L57-L62.  We would like to either get this patch merged upstream to allow `llvm` to support alternate `glibc` locations, or see if it is possible to use a LLVM configuration file to achieve this instead: https://clang.llvm.org/docs/UsersManual.html#configuration-files.  Until either one of these is achieved I don't think this can fixed at the moment, so I'm closing this until we've made progress in one of those directions.

**Closed by danielnachun** 2021-03-27 01:04 UTC
