### ISSUE TITLE
mpv failed to build on Ubuntu 16.04.7 LTS (KDE neon)

### ISSUE THREAD

**Issue by codemedic** [Homebrew/linuxbrew-core#22124] opened 2021-01-19 13:23 UTC
# Bug report

Upgrading `mpv 0.33.0_2 -> 0.33.0_3` failed.

NB: `mpv` has been segfaulting since the last update. I recreated the entire linuxbrew installation and that did not fix the crash.

The result of `brew gist-logs mpv` can be [found here](https://gist.github.com/codemedic/454284f680dc9720346a178ccfa92192).

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? 
  Resolved as many as possible; the remaining are related to the package being upgraded.
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrading `mpv 0.33.0_2 -> 0.33.0_3` since `v0.33.0_2` has been segfaulting since upgrade and reinstallation.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

~$ brew upgrade mpv
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 33dafa449 to 50cd83642.
No changes to formulae.

==> Upgrading 1 outdated package:
mpv 0.33.0_2 -> 0.33.0_3
==> Upgrading mpv 0.33.0_2 -> 0.33.0_3
==> Downloading https://github.com/mpv-player/mpv/archive/v0.33.0.tar.gz
Already downloaded: /home/dkorah/.cache/Homebrew/downloads/f6937178245c8f6e0c27b5fe64ae9faf92223a5083c4b822f882377d3ecd0e88--mpv-0.33.0.tar.gz
==> /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3 bootstrap.py
==> /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3 waf configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/mpv/0.33.0_3 --enable-html-build --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchive --enable-uchardet --confdir=/home/linuxbrew/.linux
==> /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3 waf install
Last 15 lines from /home/dkorah/.cache/Homebrew/Logs/mpv/03.python3:
- install /home/linuxbrew/.linuxbrew/etc/mpv/encoding-profiles.conf (from etc/encoding-profiles.conf)
+ install /home/linuxbrew/.linuxbrew/Cellar/mpv/0.33.0_3/share/mpv/icons/hicolor/16x16/apps/mpv.png (from etc/mpv-icon-8bit-16x16.png)
+ install /home/linuxbrew/.linuxbrew/Cellar/mpv/0.33.0_3/share/mpv/icons/hicolor/32x32/apps/mpv.png (from etc/mpv-icon-8bit-32x32.png)
[ 44/484] Compiling video/out/vo_x11.c
[ 45/484] Compiling video/out/vo_xv.c
gcc-5: error: 100000000: No such file or directory
gcc-5: error: unrecognized command line option '-image_base'

gcc-5: error: 100000000: No such file or directory
gcc-5: error: unrecognized command line option '-image_base'

Waf: Leaving directory `/tmp/mpv-20210119-18242-1hfx908/mpv-0.33.0/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)

READ THIS: https://docs.brew.sh/Troubleshooting

  </pre>
</details>

## What you expected to happen

The upgrade to work.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew update && brew upgrade mpv`

**Comment by danielnachun** [comment] 2021-01-23 02:52
This is failing because the dependency has `luajit-openresty` has macOS-specific linker options added to its `pkgconfig` file that need to made macOS-only.  I will make a pull request to fix this.  Since it is already bottled on Linux, the bottle will also need to be rebuilt.

**Comment by danielnachun** [comment] 2021-01-28 19:08
This should now be fixed by https://github.com/Homebrew/homebrew-core/pull/69698.  It turns out the linker flags causing this error aren't even needed on macOS anymore.  The install of `mpv` now works locally for me.  Please try again and close the issue if the problem is resolved.

**Comment by danielnachun** [comment] 2021-02-01 05:24
I'm going to close this since it should be fixed now.  If you still have problems you can open a new issue.

**Closed by danielnachun** 2021-02-01 05:24 UTC
