### ISSUE TITLE
Screen 4.6.2 Build From Source Failing On Linux

### ISSUE THREAD

**Issue by tundratim** [Homebrew/linuxbrew-core#13358] opened 2019-05-28 19:14 UTC
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)
Build screen 4.6.2 from source on Linux

# What happened (include command output)
Build logic computes new temporary directory name, but never actually creates it.  This causes subsequent untar to fail

```
==> Verifying 31dbebcad80655ac1835de1e48582a82a29ff9effa7f3c3fb9b4ab4b0f45f3f0--screen-4.6.2.tar.gz checksum
tar xof /home/test/.cache/Homebrew/downloads/31dbebcad80655ac1835de1e48582a82a29ff9effa7f3c3fb9b4ab4b0f45f3f0--screen-4.6.2.tar.gz -C /tmp/d20190528-17030-1wxctk1
cp -pR /tmp/d20190528-17030-1wxctk1/screen-4.6.2/. /tmp/screen-20190528-17030-r4ftfa/screen-4.6.2
chmod -Rf +w /tmp/d20190528-17030-1wxctk1
==> Downloading https://gist.githubusercontent.com/yujinakayama/4608863/raw/75669072f227b82777df25f99ffd9657bd113847/gistfile1.diff
Already downloaded: /home/test/.cache/Homebrew/downloads/4b52c981266437250af3c28ffe12c641eb1bc1654ad0cf6abde18c6c6590c891--gistfile1.diff
==> Verifying 4b52c981266437250af3c28ffe12c641eb1bc1654ad0cf6abde18c6c6590c891--gistfile1.diff checksum
==> Patching
cp -p /home/test/.cache/Homebrew/downloads/4b52c981266437250af3c28ffe12c641eb1bc1654ad0cf6abde18c6c6590c891--gistfile1.diff /tmp/screen--patch-20190528-17030-1ojzspg/gistfile1.diff
==> Applying gistfile1.diff
patch -g 0 -f -p2 -i /tmp/screen--patch-20190528-17030-1ojzspg/gistfile1.diff
Error: Failure while executing; `patch -g 0 -f -p2 -i /tmp/screen--patch-20190528-17030-1ojzspg/gistfile1.diff` exited with 1.
t
```
  
  
  

# What you expected to happen

# Step-by-step reproduction instructions (by running `brew` commands)

**Comment by issyl0** [comment] 2019-05-29 16:41
Hi, @tundratim. We probably need more information about your setup to try and reproduce this. Could you please post the output of `brew doctor` and `brew config`, as the issue template requests?

**Comment by tundratim** [comment] 2019-06-02 14:31
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /bin/pkg-config

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this unsupported configuration.
brew config
HOMEBREW_VERSION: 2.1.4-33-g7bcd70b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7bcd70b29b04b31aa74929866c6d9f2e3479b1b9
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: b7c88752fb599662ea86734ef411199ec83a2d42
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /opt/TundraWare/tools
HOMEBREW_CELLAR: /opt/TundraWare/tools/Cellar
HOMEBREW_CACHE: /home/test/.cache/Homebrew
HOMEBREW_LOGS: /home/test/.cache/Homebrew/Logs
HOMEBREW_REPOSITORY: /opt/TundraWare/tools
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_SYSTEM_CURL_TOO_OLD: 1
CPU: hexa-core 64-bit unknown_0x10_0xa
Homebrew Ruby: 2.3.7 => /opt/TundraWare/tools/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.21.0 => /opt/TundraWare/tools/bin/git
Curl: 7.65.0 => /opt/TundraWare/tools/opt/curl/bin/curl
Kernel: Linux 4.15.0-43-generic x86_64 GNU/Linux
OS: CentOS Linux release 7.6.1810 (Core) 
Host glibc: 2.17
/usr/bin/gcc: N/A
glibc: 2.23
gcc: 5.5.0_4
xorg: N/A

**Comment by issyl0** [comment] 2019-06-03 17:33
Thanks. Your system won’t install the binaries of formulae that we provide, so it’s something in the source build going wrong. I’ll look into this, and try to reproduce it.

**Comment by jonchang** [comment] 2019-06-03 17:51
The build is failing on the patch step. This shouldn't be happening unless you have a nonstandard version of `patch`.

**Comment by tundratim** [comment] 2019-06-03 23:19
@issyl0  You are correct.  I have a system setup for building brew binaries from source for Linux so that I can install them in the directory of choice rather than installing binaries in the default location.

The screen build never failed in the past.  My best assessment after a quick look at the output is that the formula is failing to build because - after it computes a new tempdir name for the work - it does not actually create it.

**Comment by tundratim** [comment] 2019-06-03 23:21
@jonchang I do not believe patch to be the culprint.  First of all, a fairly recent copy of gpatch is installed on the build system.   Also, this formula has always worked in the past.  See my commnets to @issyl0 above as to possible/likely culprit.

**Comment by issyl0** [comment] 2019-06-06 06:22
I tried this in a Centos 7 Docker container with a non-standard install path like yours, and `brew install screen` succeeded with no errors. Based on this investigation, I think @jonchang is right that it's something in your setup.

If you manage to debug further and get it working, please do leave further comments, but for now I'm going to close this issue as we can't reproduce it to be able to fix it.

**Closed by issyl0** 2019-06-06 06:22 UTC

**Comment by tundratim** [comment] 2019-06-07 00:34
@issy @jonchang You were right but not in the way you might have thought.  To understand why, you have to know how I build the distribution.  I first build a minimal brew environment (at the target location) using native compiler and build chains.  I then take a tarball snapshot of that minimal environment to a new docker container that has no native build tools on it and use that brew environment to compile everything else I want.  That way I know the brew-built binaries have few- or now system tooling dependencies for deployment.

The problem is that my self-bootstrapping environment did not have patch on it at all.  (Did I never need patch before, I wonder?)  Anyway, installing patch fixed the problem.   Thanks.

**Comment by tundratim** [comment] 2019-06-21 19:39
Reopening this...

I have discovered the root cause but do not have a fix.

The version of "patch" that ships with brew is somehow incompatible with the patch set provided to build 'screen'.   If I install the distro's version of patch (CentOS 7) everything works just fine.
