### ISSUE TITLE
Brew install mongodb fails: Error building mongoreplay

### ISSUE THREAD

**Issue by ecrvnr** [Homebrew/linuxbrew-core#13637] opened 2019-06-14 15:32 UTC
As mentioned in #12582 

> * [x]  are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
> * [x]  have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
> * [x]  ran `brew update` and can still reproduce the problem?
> * [x]  ran `brew doctor`, fixed all issues and can still reproduce the problem?
> * [x]  ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
>   https://gist.github.com/000d0ca5027dc8d102e22dba85486f36
> * [x]  if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
>   N/A
> 
> To help us debug your issue please explain:
> 
> * What you were trying to do (and why)
>   brew install mongodb
> * What happened (include command output)
> 
> ```
> ==> Downloading https://fastdl.mongodb.org/src/mongodb-src-r4.0.3.tar.gz
> Already downloaded: /home/ubuntu/.cache/Homebrew/downloads/74ae15923c12b036ac85b5b3ce6ee5f926b35df049702b8262ce7d0e976f3599--mongodb-src-r4.0.3.tar.gz
> ==> Downloading https://files.pythonhosted.org/packages/cd/b0/c2d700252fc251e91c08639ff41a8a5203b627f4e0a2ae18a6b662ab32ea/Cheetah-2.4.4.tar.gz
> Already downloaded: /home/ubuntu/.cache/Homebrew/downloads/c52e4f886933984a2acee5548875e73402354db77f43459cc2d4d9c3d29959cb--Cheetah-2.4.4.tar.gz
> ==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/mongodb-20190416-24823-c62r0k/mongodb-src-r4.0.3/vendor --install-scripts=/tmp/mongodb-20190416-24823-c62r0k/mongodb-src-r4.0.
> ==> Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz
> Already downloaded: /home/ubuntu/.cache/Homebrew/downloads/727334bb3bb982386aa982ded847f9d71b2e6cbc42488534f20c44d36812ad77--PyYAML-3.13.tar.gz
> ==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/mongodb-20190416-24823-c62r0k/mongodb-src-r4.0.3/vendor --install-scripts=/tmp/mongodb-20190416-24823-c62r0k/mongodb-src-r4.0.
> ==> Downloading https://files.pythonhosted.org/packages/bf/9b/2bf84e841575b633d8d91ad923e198a415e3901f228715524689495b4317/typing-3.6.6.tar.gz
> Already downloaded: /home/ubuntu/.cache/Homebrew/downloads/3f3cc6492e2dbcf8a0fb5ea5ac1637e17f0afb3483a5b8309638286f3a638974--typing-3.6.6.tar.gz
> ==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/mongodb-20190416-24823-c62r0k/mongodb-src-r4.0.3/vendor --install-scripts=/tmp/mongodb-20190416-24823-c62r0k/mongodb-src-r4.0.
> ==> ./build.sh ssl
> Last 15 lines from /home/ubuntu/.cache/Homebrew/Logs/mongodb/04.build.sh:
> mongodump version: 4.0.3
> Building mongotop...
> mongotop version: 4.0.3
> Building mongoreplay...
> # github.com/google/gopacket/pcap
> vendor/src/github.com/google/gopacket/pcap/pcap.go:173:7: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
> vendor/src/github.com/google/gopacket/pcap/pcap.go:384:13: identifier "_Ctype_struct_pcap_stat" may conflict with identifiers generated by cgo
> vendor/src/github.com/google/gopacket/pcap/pcap.go:421:49: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
> vendor/src/github.com/google/gopacket/pcap/pcap.go:444:10: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
> vendor/src/github.com/google/gopacket/pcap/pcap.go:462:41: identifier "_Ctype_struct_bpf_insn" may conflict with identifiers generated by cgo
> vendor/src/github.com/google/gopacket/pcap/pcap.go:538:66: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
> vendor/src/github.com/google/gopacket/pcap/pcap.go:551:19: identifier "_Ctype_struct_bpf_insn" may conflict with identifiers generated by cgo
> vendor/src/github.com/google/gopacket/pcap/pcap.go:659:34: identifier "_Ctype_struct_pcap_addr" may conflict with identifiers generated by cgo
> vendor/src/github.com/google/gopacket/pcap/pcap.go:662:56: identifier "_Ctype_struct_pcap_addr" may conflict with identifiers generated by cgo
> Error building mongoreplay
> 
> READ THIS: https://docs.brew.sh/Troubleshooting
> ```
> 
> * What you expected to happen
>   no error
> * Step-by-step reproduction instructions (by running `brew install` commands)
>   brew install mongodb

I'm making a new issue because the other one was closed.

**Comment by issyl0** [comment] 2019-06-14 18:06
Thanks for letting us know it's still a problem, @ecrvnr. This issue is a duplicate of #12582, though, so I'm going to re-open that one as it's got more context, and close out this one.

**Closed by issyl0** 2019-06-14 18:06 UTC
