### ISSUE TITLE
open-mpi (ffmpeg dependency) not installing from source on Linux Mint 19.2

### ISSUE THREAD

**Issue by Moonbase59** [Homebrew/linuxbrew-core#14767] opened 2019-08-11 05:38 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs open-mpi` (where `open-mpi` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
  Try to install `open-mpi` since it’s a dependency for `ffmpeg` which in turn is a dependency for my `loudgain`.

- What happened (include command output)
```
==> Downloading https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.1.tar.bz2
Already downloaded: /home/matthias/.cache/Homebrew/downloads/06441b124d088edf06929dec0c12aa39897d6b5353863404590fec0fa833abcc--openmpi-4.0.1.tar.bz2
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_2 --disable-silent-rules --enable-ipv6 --with-libevent=/home/linuxbrew/.linuxbrew/opt/libevent --with-sge --enable-mpi1-compatibility
==> make all
==> make check
Last 15 lines from /home/matthias/.cache/Homebrew/Logs/open-mpi/03.make:
============================================================================
Makefile:2154: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/tmp/open-mpi-20190811-7210-w7afb0/openmpi-4.0.1/test/util'
Makefile:2260: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/tmp/open-mpi-20190811-7210-w7afb0/openmpi-4.0.1/test/util'
Makefile:2347: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/tmp/open-mpi-20190811-7210-w7afb0/openmpi-4.0.1/test/util'
Makefile:1756: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/tmp/open-mpi-20190811-7210-w7afb0/openmpi-4.0.1/test'
Makefile:1893: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
open-mpi: Build a bottle for Linuxbrew https://github.com/Homebrew/linuxbrew-core/pull/14719
```

- What you expected to happen
  open-mpi installed cleanly (actually, ffmpeg installed but as requested, tried only _one_ formula).

- Step-by-step reproduction instructions (by running `brew install` commands)
  ```bash
  brew install open-mpi
  brew install open-mpi --env=std
  ```
  (Both didn’t work.)

Gist as requested: https://gist.github.com/64675b0cb84cea491d066fd7f91f4e24

**Comment by Moonbase59** [comment] 2019-08-11 06:10
In the meantime, I also tried:
```bash
brew install --HEAD open-mpi
```

Gets me almost the same error:
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Cloning https://github.com/open-mpi/ompi.git
Cloning into '/home/matthias/.cache/Homebrew/open-mpi--git'...
==> Checking out branch master
Your branch is up to date with 'origin/master'.
Already on 'master'
==> ./autogen.pl
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/open-mpi/HEAD-6159afc
==> make all
==> make check
Last 15 lines from /home/matthias/.cache/Homebrew/Logs/open-mpi/04.make:
============================================================================
Makefile:2126: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/tmp/open-mpi-20190811-24820-aidcmd/test/util'
Makefile:2232: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/tmp/open-mpi-20190811-24820-aidcmd/test/util'
Makefile:2322: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/tmp/open-mpi-20190811-24820-aidcmd/test/util'
Makefile:1720: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/tmp/open-mpi-20190811-24820-aidcmd/test'
Makefile:1857: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
open-mpi: Build a bottle for Linuxbrew https://github.com/Homebrew/linuxbrew-core/pull/14719
open-mpi (ffmpeg dependency) not installing from source on Linux Mint 19.2 https://github.com/Homebrew/linuxbrew-core/issues/14767
```

**Comment by iMichka** [comment] 2019-08-11 13:21
I build a bottle for `open-mpi` in #14719.
Please update and try again.

We have no issue compiling this. If this still fails, the best bet is to open an issue upstream (on the `open-mpi` bug tracker).

**Comment by Moonbase59** [comment] 2019-08-11 13:26
Wow, FAST response, thanks for the x86_64_linux bottles, helped a lot.
Not only open-mpi but also the complete ffmpeg is now available in a few seconds, not hours.

Solves the problem for now, but I still wonder why it didn’t compile in the first place.

**Comment by iMichka** [comment] 2019-08-11 13:43
Cool, glad it works for you.

Compiling things from source can be difficult. It can be anything: missing dependencies, messed up env variables, bugs, ... Here it looks like `make check` is failing. These kind of tests (for many libraries) have the bad habit to often be broken on different platforms.

If you want, you can try and sort out the root cause of this. On our side, as the bottle works, we will just close this issue (as we have other things to handle before looking at these kind of issues).

**Closed by iMichka** 2019-08-11 13:43 UTC
Labels: formula/build error
