### ISSUE TITLE
Error with qt installation

### ISSUE THREAD

**Issue by ptitle** [Homebrew/linuxbrew-core#12857] opened 2019-04-28 17:43 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

gist-log: https://gist.github.com/4297799f8d9b6ebc53a27f1341ce6ac2

Tried installing qt as it is a dependency for poppler, which itself is a dependency for gdal, which is I am primarily trying to install.
Output is as follows: 
```
brew install qt
==> Downloading https://download.qt.io/official_releases/qt/5.12/5.12.2/single/qt-every
Already downloaded: /home/pascaltitle/.cache/Homebrew/downloads/e5a2d7ee7f598b577626dc985c25e12295b25bda81034b73b235541875d3bd4d--qt-everywhere-src-5.12.2.tar.xz

Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
qtbase/src/gui/configure.json:
  expected replacement of "[ \"xcb/xcb.h\", \"X11/Xlib.h\", \"X11/Xlib-xcb.h\" ]," with "[ \"xcb/xcb.h\", \"X11/Xlib.h\", \"X11/Xlib-xcb.h\", \"xcb/shm.h\" ],"

```

**Comment by Char-Aznable** [comment] 2019-04-28 19:03
I have got the same error. The patch in the formula doesn't work anymore. I have got a hacky work around: modify the platform config of qmake by appneding to the linker flags "-lxcb-shm" -- this is ugly but it works.

**Comment by iMichka** [comment] 2019-04-28 20:48
Duplicate of #11696.

I was not really able to get help from upstream.

I found also a way by hacking some qmake file and added "-lxcb-shm" manually. We can discuss this further in the PR.

**Closed by iMichka** 2019-04-28 20:48 UTC

**Comment by anishmittal2020** [comment] 2019-04-29 17:27
@Char-Aznable   I am a beginner could you please tell me how to do "modify the platform config of qmake by appneding to the linker flags "-lxcb-shm" ", as you said in more details. Thanks

**Comment by Char-Aznable** [comment] 2019-04-30 22:52
@anishmittal2020 I basically did what @iMichka did in hist recent post at https://bugreports.qt.io/browse/QTBUG-74874?focusedCommentId=458208&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-458208
