### ISSUE TITLE
Can't upgrade gdk-pixbuf from 2.38.0_1 -> 2.38.1

### ISSUE THREAD

**Issue by olikami** [Homebrew/linuxbrew-core#11997] opened 2019-03-10 12:48 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Linuxbrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/linuxbrew-core formula on Linux? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a tap (e.g. brewsci/homebrew-bio) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/de68fd1380a05bf235fec234356bfc6f
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
`brew upgrade`
- What happened (include command output)
```
$ brew upgrade
==> Upgrading 1 outdated package:
gdk-pixbuf 2.38.0_1 -> 2.38.1
==> Upgrading gdk-pixbuf 
==> Downloading https://download.gnome.org/sources/gdk-pixbuf/2.38/gdk-pixbuf-2.38.1.tar.xz
==> Downloading from https://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.gnome.org/sources/gdk-pixbuf/2.38/gdk-pixbuf-2.38.1.tar.xz
######################################################################## 100.0%
Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
gdk-pixbuf/meson.build:
  expected replacement of "  bin = executable(bin_name, bin_source,\n                   dependencies: gdk_pixbuf_deps + [ gdkpixbuf_dep ],\n                   include_directories: [ root_inc, gdk_pixbuf_inc ],\n                   c_args: common_cflags + gdk_pixbuf_cflags,\n                   install: true)" with "  bin = executable(bin_name, bin_source,\n                   dependencies: gdk_pixbuf_deps + [ gdkpixbuf_dep ],\n                   include_directories: [ root_inc, gdk_pixbuf_inc ],\n                   c_args: common_cflags + gdk_pixbuf_cflags,\n                   install: true, install_rpath: '/home/linuxbrew/.linuxbrew/Cellar/gdk-pixbuf/2.38.1/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/python/lib:/home/linuxbrew/.linuxbrew/opt/ncurses/lib:/home/linuxbrew/.linuxbrew/opt/zlib/lib:/home/linuxbrew/.linuxbrew/opt/gettext/lib:/home/linuxbrew/.linuxbrew/opt/libffi/lib:/home/linuxbrew/.linuxbrew/opt/bzip2/lib:/home/linuxbrew/.linuxbrew/opt/pcre/lib:/home/linuxbrew/.linuxbrew/opt/gdbm/lib:/home/linuxbrew/.linuxbrew/opt/openssl/lib:/home/linuxbrew/.linuxbrew/opt/readline/lib:/home/linuxbrew/.linuxbrew/opt/sqlite/lib:/home/linuxbrew/.linuxbrew/opt/xz/lib:/home/linuxbrew/.linuxbrew/opt/python@2/lib:/home/linuxbrew/.linuxbrew/opt/util-linux/lib:/home/linuxbrew/.linuxbrew/opt/glib/lib:/home/linuxbrew/.linuxbrew/opt/jpeg/lib:/home/linuxbrew/.linuxbrew/opt/libpng/lib:/home/linuxbrew/.linuxbrew/opt/libtiff/lib:/home/linuxbrew/.linuxbrew/opt/libxml2/lib')"
```
- What you expected to happen
`brew upgrade` runs normally and upgrades gdk-pixbuf.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install gdk-pixbuf` should probably give the same error.

**Comment by iMichka** [comment] 2019-03-10 19:58
Duplicate of #11862

**Closed by iMichka** 2019-03-10 19:58 UTC
