### ISSUE TITLE
Cannot update openssl@1.1 because their test fails

### ISSUE THREAD

**Issue by StudioMaX** [Homebrew/linuxbrew-core#22015] opened 2021-01-03 18:05 UTC
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Update any formula which has a dependency on `openssl@1.1`, or just `brew upgrade openssl@1.1`. OpenSSL must be updated to the latest `1.1.1i`

## What happened (include command output)

An error occurred while executing `make test` here:
https://github.com/Homebrew/linuxbrew-core/blob/fd44ef07c79376048fe620765464fa4f6ae7ec72/Formula/openssl%401.1.rb#L108

https://gist.github.com/StudioMaX/34880cfff7c683e6d865268e3f7cde3b

At first I thought it had something to do with my Ubuntu 16.04 and some sort of bug with tests in OpenSSL, so I created this bug in upstream: https://github.com/openssl/openssl/issues/13758. Please read this first.

After some research I found that during the `make test` a new compiled `./apps/openssl` binary is executed, but it loads additional shared libraries `libssl.so.1.1` and `libcrypto.so.1.1` from the previously installed OpenSSL `1.1.1g`, although it should find new libraries in the root directory where OpenSSL was compiled.

```
linuxbrew@host:~/tmp/openssl-1.1.1i$ ./apps/openssl version
OpenSSL 1.1.1i  8 Dec 2020 (Library: OpenSSL 1.1.1g  21 Apr 2020)

linuxbrew@host:~/tmp/openssl-1.1.1i$ ldd ./apps/openssl
        linux-vdso.so.1 =>  (0x00007fff9d19c000)
        libssl.so.1.1 => /usr/home/linuxbrew/.linuxbrew/lib/libssl.so.1.1 (0x00007fe89b814000)
        libcrypto.so.1.1 => /usr/home/linuxbrew/.linuxbrew/lib/libcrypto.so.1.1 (0x00007fe89b3bd000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe89b1b9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe89af9c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe89abd2000)
        /usr/home/linuxbrew/.linuxbrew/lib/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00007fe89b680000)
```

When running tests, OpenSSL uses an additional wrapper `./util/shlib_wrap.sh ./apps/openssl ...`, whose task is to [add LD_LIBRARY_PATH](https://github.com/openssl/openssl/blob/90cebd1b216e0a160fcfd8e0eddca47dad47c183/util/shlib_wrap.sh.in#L99-L111) before executing `./apps/openssl`, in order to first find libraries `libssl.so.1.1` and `libcrypto.so.1.1` in the openssl build directory.

But adding this environment variable does not work, since brewed gcc [adds `RPATH`](https://github.com/openssl/openssl/issues/13758#issuecomment-753641486) to the dynamic section of the binary, which points to `/usr/home/linuxbrew/.linuxbrew/lib`.
Since `RPATH` has a higher priority than `LD_LIBRARY_PATH`, the necessary libraries are first searched for in directory `/usr/home/linuxbrew/.linuxbrew/lib`, although they should be loaded from `/tmp/openssl-1.1-20210103-20036-1xvc65/openssl-1.1.1i`.

<details>
  <summary>Command output</summary>
  <pre>

```
linuxbrew@host:~/tmp/openssl-1.1.1i$ brew upgrade openssl@1.1
==> Upgrading 1 outdated package:
openssl@1.1 1.1.1g -> 1.1.1i
==> Upgrading openssl@1.1 1.1.1g -> 1.1.1i
Warning: Building openssl@1.1 from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /usr/home/linuxbrew/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /usr/home/linuxbrew/.linuxbrew)
- HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew (yours is /usr/home/linuxbrew/.linuxbrew/Homebrew)
==> Downloading https://curl.haxx.se/ca/cacert-2020-01-01.pem
Already downloaded: /usr/home/linuxbrew/.cache/Homebrew/downloads/e2b36a2c425753a7b9d6a8eccb44b33cb7ed93cb91f96dafcf35fa18d8e0513a--cacert-2020-01-01.pem
==> Downloading https://cpan.metacpan.org/authors/id/L/LE/LEONT/Test-Harness-3.42.tar.gz
Already downloaded: /usr/home/linuxbrew/.cache/Homebrew/downloads/4a5728e2132a470084886ad6e6278c6b23584e314ee60dcd57ea679202d5da4a--Test-Harness-3.42.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302175.tar.gz
Already downloaded: /usr/home/linuxbrew/.cache/Homebrew/downloads/af880136321fd9982d8eb9dd29977fec40c093fb2fd48d6fff85de8d6bb9a5b5--Test-Simple-1.302175.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.48.tar.gz
Already downloaded: /usr/home/linuxbrew/.cache/Homebrew/downloads/5c7e196d2435858f251597e37b63b670add424924b9e99d3079665b0628eed04--ExtUtils-MakeMaker-7.48.tar.gz
==> Downloading https://www.openssl.org/source/openssl-1.1.1i.tar.gz
Already downloaded: /usr/home/linuxbrew/.cache/Homebrew/downloads/fd23ba7b701c9f6232538758ea8cc3025119733e0e3e6f6af55517e8bdc49b0e--openssl-1.1.1i.tar.gz
==> perl Makefile.PL INSTALL_BASE=/usr/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1i/libexec
==> make PERL5LIB=/usr/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1i/libexec/lib/perl5 CC=gcc-5
==> make install
==> perl Makefile.PL INSTALL_BASE=/usr/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1i/libexec
==> make PERL5LIB=/usr/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1i/libexec/lib/perl5 CC=gcc-5
==> make install
==> perl Makefile.PL INSTALL_BASE=/usr/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1i/libexec
==> make PERL5LIB=/usr/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1i/libexec/lib/perl5 CC=gcc-5
==> make install
==> perl ./Configure --prefix=/usr/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1i --openssldir=/usr/home/linuxbrew/.linuxbrew/etc/openssl@1.1 no-ssl3 no-ssl3-method no-zlib enable-md2
==> make
==> make install MANDIR=/usr/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1i/share/man MANSUFFIX=ssl
==> make test
Last 15 lines from /usr/home/linuxbrew/.cache/Homebrew/Logs/openssl@1.1/13.make:
  Failed tests:  111-112, 144
  Non-zero exit status: 3
../test/recipes/90-test_sslapi.t                 (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/90-test_v3name.t                 (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=158, Tests=2634, 134 wallclock secs ( 2.51 usr  0.27 sys + 108.37 cusr 10.72 csys = 121.87 CPU)
Result: FAIL
Makefile:207: recipe for target '_tests' failed
make[1]: *** [_tests] Error 1
make[1]: Leaving directory '/tmp/openssl-1.1-20210103-20036-1xvc65/openssl-1.1.1i'
Makefile:205: recipe for target 'tests' failed
make: *** [tests] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting
```
  </pre>
</details>

## What you expected to happen

OpenSSL must be updated from `1.1.1g` to `1.1.1i` successfully.
I'm not sure exactly, but most likely `RPATH` shouldn't be added to the binary.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. Have previously installed `openssl@1.1` with version 1.1.1g.
2. Update to the new openssl version 1.1.1i via `brew upgrade openssl@1.1`

**Comment by StudioMaX** [comment] 2021-01-03 18:12
To be honest, I had to comment out `make test` in the `openssl@1.1` formula and upgrade successfully after that, since OpenSSL is a frequent dependency in all other formulas. Therefore, it will be difficult for me to repeat this bug again. I ask those who understand brew architecture and gcc/linker flags to confirm or deny the issue I described.

**Comment by StudioMaX** [comment] 2021-01-25 06:24
Bump

**Comment by siliconplains44** [comment] 2021-02-04 00:48
brew upgrade openssl@1.1
Error: openssl@1.1 not installed

I receive the above when I try to upgrade, is there a solution?

**Comment by koalalorenzo** [comment] 2021-03-16 10:52
Same problem here! What is the issue? :(

**Comment by koalalorenzo** [comment] 2021-03-16 10:56
This _actually_ might be useful for https://github.com/Homebrew/linuxbrew-core/issues/22225

**Comment by roock** [comment] 2021-03-18 07:57
I had similar issues while upgrading openssl.

```
==> make
==> make install MANDIR=/home/roock/.linuxbrew/Cellar/openssl@1.1/1.1.1j/share/man MANSUFFIX=ssl
==> make test
Last 15 lines from /home/roock/.cache/Homebrew/Logs/openssl@1.1/13.make:
  Non-zero exit status: 2
../test/recipes/80-test_x509aux.t                (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/90-test_sslapi.t                 (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/90-test_v3name.t                 (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=158, Tests=2635, 107 wallclock secs ( 1.94 usr  0.21 sys + 93.61 cusr 23.13 csys = 118.89 CPU)
Result: FAIL
make[1]: *** [Makefile:208: _tests] Error 1
make[1]: Leaving directory '/tmp/openssl-1.1-20210318-2622373-xmhii/openssl-1.1.1j'
make: *** [Makefile:205: tests] Error 2
```
For me the following worked:
```
brew unlink openssl 
brew upgrade  openssl
```

**Comment by lzap** [comment] 2021-03-25 12:23
Hey, this issue was recommended by brew to me, although mine is slightly different I have a solution:

```
==> Installing dependencies for ruby@2.7: openssl@1.1, gpatch, ncurses, readline and zlib
==> Installing ruby@2.7 dependency: openssl@1.1
==> perl Makefile.PL INSTALL_BASE=/home/foreman/.linuxbrew/Cellar/openssl@1.1/1.1.1j/libex
==> make PERL5LIB=/home/foreman/.linuxbrew/Cellar/openssl@1.1/1.1.1j/libexec/lib/perl5 CC=
Last 15 lines from /home/foreman/.cache/Homebrew/Logs/openssl@1.1/02.make:
2021-03-25 11:03:36 +0100

make
PERL5LIB=/home/foreman/.linuxbrew/Cellar/openssl@1.1/1.1.1j/libexec/lib/perl5
CC=gcc

Can't locate ExtUtils/Command.pm in @INC (you may need to install the ExtUtils::Command module) (@INC contains: inc blib/arch blib/lib /home/foreman/.linuxbrew/Cellar/openssl@1.1/1.1.1j/libexec/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5).
BEGIN failed--compilation aborted.
make: *** [Makefile:437: blib/lib/ExtUtils/.exists] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Cannot update openssl@1.1 because their test fails https://github.com/Homebrew/linuxbrew-core/issues/22015
```

In my case the issue is that openssl needs perl to be built, however perl needs openssl. Therefore on a system without perl or without this specific module openssl cannot be built.

In my case, I have a CentOS 8 Stream here with perl installed however without the `ExtUtils/Command.pm` module. Quick search in my package manager showed that the missing piece is indeed perl ExtUtils::Command module, so I installed it:

```
dnf install perl-ExtUtils-Command
```

And openssl now bootstrap just fine. Then brew can install its own perl and other dependencies for the software I want to install: Ruby 2.7.

I am dropping this here just for a record, this is probably a different issue but since brew recommends it people with the very same problem like me (installing Ruby 2.7) might land over here. Cheers!

**Comment by danielnachun** [comment] 2021-03-26 23:47
@lzap this is a different issue which we should address.  We already add some other Perl dependencies to make `opennessl` build but `ExtUtils::Command` is not one of them.  Can you open a separate issue for this so I can remember to add that as a resource?

**Comment by danielnachun** [comment] 2021-03-27 00:33
There's a couple of issues here that need to be address:

1) The default cellar for Homebrew on Linux is `/home/linuxbrew/.linuxbrew`, not `/usr/home/linuxbrew/linuxbrew`.  If you have the permissions to install Homebrew into the default location, please install there so that you can use non-relocatable bottles (one of which is `openssl`).  

2) Regarding the original issue, while `openssl` is being built it should delete the symlinks from the `openssl` cellar into `$HOMEBREW_PREFIX/lib`, preventing anything in the build process from finding the old libraries.  You could try running `brew unlink openssl@1.1` before trying to upgrade and see if that fixes the problem.  That's not a permanent solution but would give us a better idea of why this is happening.

**Comment by lzap** [comment] 2021-04-14 12:51
@danielnachun here you go: https://github.com/Homebrew/linuxbrew-core/issues/22985

**Comment by StudioMaX** [comment] 2021-05-25 12:34
As far as I know this hasn't been fixed yet.

**Comment by cbagwell** [comment] 2021-07-30 21:44
I had the same `make test` failure during upgrade.  Running `brew unlink openssl@1.1` followed by `brew upgrade openssl@1.1` did work around the issue.

```
../test/recipes/80-test_x509aux.t                (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/90-test_sslapi.t                 (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/90-test_v3name.t                 (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=158, Tests=2635, 103 wallclock secs ( 1.78 usr  0.16 sys + 76.46 cusr 21.81 csys = 100.21 CPU)
Result: FAIL
make[1]: *** [_tests] Error 1
make[1]: Leaving directory `/tmp/opensslA1.1-20210730-30874-1tsu2jp/openssl-1.1.1k'
make: *** [tests] Error 2
```

**Comment by MikeMcQuaid** [comment] 2021-08-17 10:58
Closing, sorry. If this issue is still relevant: please reopen on homebrew-core.

**Closed by MikeMcQuaid** 2021-08-17 10:58 UTC
