### ISSUE TITLE
git 2.28.0 bottle is broken

### ISSUE THREAD

**Issue by metcalfc** [Homebrew/linuxbrew-core#20827] opened 2020-07-28 15:56 UTC
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/92af5b5c6cdb3aa1d8a6fc84ff9dda49
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Update to git 2.28.0.

## What happened (include command output)

Installed and by default use the bottle and the binary doesn't work.

<details>
  <summary>Command output</summary>
  <pre>
git status
error: git died of signal 4
  </pre>
</details>

## What you expected to happen

I expected to see the git output that the working tree was clean.

## Step-by-step reproduction instructions (by running `brew install` commands)

Repro with workaround (ie don't use the broken bottle).

<details>
  <summary>Command output</summary>
  <pre>
brew install git
git status
error: git died of signal 4
brew uninstall git
brew install -s git
git status
On branch main
nothing to commit, working tree clean
  </pre>
</details>

**Comment by iMichka** [comment] 2020-07-28 16:00
Duplicate of #20826

**Closed by iMichka** 2020-07-28 16:00 UTC
