### ISSUE TITLE
Git won't work anymore, any action results in "died of signal 4". This also breaks `brew update`.

### ISSUE THREAD

**Issue by tsela** [Homebrew/linuxbrew-core#20826] opened 2020-07-28 15:37 UTC
- [x] ran `brew update` and can still reproduce the problem? (`brew update` fails)
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

After the last brew upgrade (with git installed via brew), I tried cloning a repository with `git clone`.

## What happened (include command output)

I got the following error:

```shell
$ git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.8
Cloning into '/home/christophe/.asdf'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (60/60), done.
error: index-pack died of signal 4
fatal: index-pack failed

```

Worse, `brew update` won't work anymore either. I get the following error:

```shell
$ brew update
error: rev-list died of signal 4
fatal: the remote end hung up unexpectedly
Error: Fetching /home/linuxbrew/.linuxbrew/Homebrew failed!
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update.sh: line 17:  6056 Illegal instruction     (core dumped) "$GIT_EXECUTABLE" "$@"
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update.sh: line 17:  6058 Illegal instruction     (core dumped) "$GIT_EXECUTABLE" "$@"
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/update.sh: line 17:  6063 Illegal instruction     (core dumped) "$GIT_EXECUTABLE" "$@"

```

## What you expected to happen

I expected to be able to use git normally.

## Step-by-step reproduction instructions (by running `brew install` commands)

I just upgraded git and everything else installed under homebrew using `brew update` and `brew upgrade`. It upgraded git to the latest version on Homebrew, as well as a few other packages.

`brew doctor`:

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

```

I cannot remove the symlink, I need it for Poetry to run correctly.

`brew gist-logs git`:

```shell
$ brew gist-logs git
Error: No logs.

```

`brew config`:

```shell
$ brew config
HOMEBREW_VERSION: >=2.2.0 (shallow or no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: e6b066a3d9fc5435009428fcd2855fddf9b455c0
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 6078c8ecfc37e0a4d8dc32a71ad60fba5ef27356
Core tap last commit: 87 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :1
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: N/A
Git: 2.28.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-42-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.1 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
glibc: N/A
gcc: N/A
xorg: N/A

```

Also `brew list` if it helps:

```shell
$ brew list 
autoconf     bzip2  expat  gettext  libbsd  linux-headers  ncurses	patchelf  perl	      python@3.8  sqlite  xz
berkeley-db  curl   gdbm   git	    libffi  m4		   openssl@1.1	pcre2	  pkg-config  readline	  unzip   zlib
```

I hope you can help quickly. With git broken like that I cannot do anything anymore!

**Comment by iMichka** [comment] 2020-07-28 16:04
Thanks for the report. I can reproduce.

Quick workaround:
> brew uninstall git && brew install git -s

This error is likely due to https://github.com/Homebrew/brew/pull/8119

**Comment by iMichka** [comment] 2020-07-28 16:56
Fixed by #20828. Initial culprit was https://github.com/Homebrew/brew/pull/8112, which was then fixed by https://github.com/Homebrew/brew/pull/8119.

**Closed by iMichka** 2020-07-28 16:56 UTC

**Comment by sjackman** [comment] 2020-07-28 16:59
This bug has been resolved by PR https://github.com/Homebrew/linuxbrew-core/pull/20828

With Git in a broken state, follow these instructions to get it working again, if you have a new enough version of Git provided by your host system (`/usr/bin/git`):
```bash
brew remove git
brew update
brew install git
```

**Comment by sjackman** [comment] 2020-07-28 17:02
With Git in a broken state, follow these instructions to get it working again, if you _do not_ have a new enough version of Git provided by your host system (/usr/bin/git):
```bash
brew remove git
HOMEBREW_NO_AUTO_UPDATE=1 brew install https://dl.bintray.com/linuxbrew/bottles/git-2.28.0_1.x86_64_linux.bottle.tar.gz
brew update
```

**Comment by tsela** [comment] 2020-07-28 21:10
Great! Everything is working again. Thanks for the very quick reaction!
