### ISSUE TITLE
Error in dependenciy llvm@4 while installing pcl 

### ISSUE THREAD

**Issue by danielaDESM** [Homebrew/linuxbrew-core#10371] opened 2018-11-19 17:42 UTC
```
brew gist-logs llvm@4
https://gist.github.com/danielaDESM/1c4a77a86bb902cf82a0416742849ddd
==> cmake -G Unix Makefiles .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAG
==> make
Last 15 lines from /home/daniela/.cache/Homebrew/Logs/llvm@4/02.make:
cd /tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/lib/ReaderWriter/MachO && /home/daniela/.linuxbrew/opt/gcc/bin/g++  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/lib/ReaderWriter/MachO/.  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -DNDEBUG     -o CMakeFiles/lldMachO.dir/StubsPass.cpp.o -c /tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/lib/ReaderWriter/MachO/StubsPass.cpp
[ 20%] Building CXX object tools/lld/lib/ReaderWriter/MachO/CMakeFiles/lldMachO.dir/TLVPass.cpp.o
cd /tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/lib/ReaderWriter/MachO && /home/daniela/.linuxbrew/opt/gcc/bin/g++  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/lib/ReaderWriter/MachO/.  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -DNDEBUG     -o CMakeFiles/lldMachO.dir/TLVPass.cpp.o -c /tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/lib/ReaderWriter/MachO/TLVPass.cpp
[ 20%] Building CXX object tools/lld/lib/ReaderWriter/MachO/CMakeFiles/lldMachO.dir/WriterMachO.cpp.o
cd /tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/lib/ReaderWriter/MachO && /home/daniela/.linuxbrew/opt/gcc/bin/g++  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/include -I/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/lib/ReaderWriter/MachO/.  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -DNDEBUG     -o CMakeFiles/lldMachO.dir/WriterMachO.cpp.o -c /tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/tools/lld/lib/ReaderWriter/MachO/WriterMachO.cpp
[ 20%] Linking CXX static library ../../../../../lib/liblldMachO.a
cd /tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/lib/ReaderWriter/MachO && /home/daniela/.linuxbrew/Cellar/cmake/3.12.4/bin/cmake -P CMakeFiles/lldMachO.dir/cmake_clean_target.cmake
cd /tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/lib/ReaderWriter/MachO && /home/daniela/.linuxbrew/Cellar/cmake/3.12.4/bin/cmake -E cmake_link_script CMakeFiles/lldMachO.dir/link.txt --verbose=1
/home/daniela/.linuxbrew/bin/ar qc ../../../../../lib/liblldMachO.a  CMakeFiles/lldMachO.dir/ArchHandler.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_arm.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_arm64.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_x86.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_x86_64.cpp.o CMakeFiles/lldMachO.dir/CompactUnwindPass.cpp.o CMakeFiles/lldMachO.dir/GOTPass.cpp.o CMakeFiles/lldMachO.dir/LayoutPass.cpp.o CMakeFiles/lldMachO.dir/MachOLinkingContext.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileBinaryReader.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileBinaryWriter.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileFromAtoms.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileToAtoms.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileYAML.cpp.o CMakeFiles/lldMachO.dir/ObjCPass.cpp.o CMakeFiles/lldMachO.dir/ShimPass.cpp.o CMakeFiles/lldMachO.dir/StubsPass.cpp.o CMakeFiles/lldMachO.dir/TLVPass.cpp.o CMakeFiles/lldMachO.dir/WriterMachO.cpp.o
/home/daniela/.linuxbrew/bin/ranlib ../../../../../lib/liblldMachO.a
make[2]: Leaving directory '/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build'
[ 20%] Built target lldMachO
make[1]: Leaving directory '/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2
```
**brew config**
HOMEBREW_VERSION: 1.8.2-1-g9769fb2
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 9769fb22fe2cef2dc00420111fd4ecf5b19e5c0d
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: c7e37d57f0655d422f9a6eb2d225836bca3d7cfa
Core tap last commit: 22 hours ago
HOMEBREW_PREFIX: /home/daniela/.linuxbrew
HOMEBREW_REPOSITORY: /home/daniela/.linuxbrew
HOMEBREW_CELLAR: /home/daniela/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/daniela/.cache/Homebrew
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /home/daniela/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Kernel: Linux 4.15.0-39-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.5 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: 5.5.0_4
xorg: 20170115_1

 **brew doctor**
Your system is ready to brew.

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by danielaDESM** [comment] 2018-11-19 18:51
I am so sorry, I can't. I tried couple of times but it keeps sending an error after I export the token to the bash:
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.bash_profile
(with the token generated in https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew)
In the terminal, it asks my username and password, but it does not work. Like if I am giving the wrong, but I have verified through the web browser. I tried with my username and pass, and with my email and pass.

**Comment by maxim-belkin** [comment] 2018-11-19 18:55
Make sure you source (`.`) the right file: I used `~/.bashrc` in my example. You used `~/.bash_profile` in yours. You can also simply execute that `export ...` command in the current shell and then do `brew gist-logs llvm@4`

**Comment by danielaDESM** [comment] 2018-11-19 19:11
Error: GitHub Bad credentials:HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check:
https://github.com/settings/tokens

I have regenerated the token 3 times.

**Comment by maxim-belkin** [comment] 2018-11-19 19:38
1. Edit your `~/.bashrc` and `~/.bash_profile` and delete all `export HOMEBREW_GITHUB_API_TOKEN` lines there.
1. Start a new Terminal session
1. Execute `compgen -A variable HOMEBREW` and make sure you do NOT have any `HOMEBREW` variables (empty output).
1. Execute: `cd $(brew --repo) && git clean -dfx && git pull origin master`
1. Go to https://github.com/settings/tokens and delete all tokens there
1. Generate a new token and save it somewhere (to a text file)
1. Execute `export HOMEBREW_GITHUB_API_TOKEN=...` in your terminal shell
1. Execute `brew gist-logs llvm@4`
And let me know if it still fails to create a gist-log.

**Comment by danielaDESM** [comment] 2018-11-19 19:49
It worked. Thanks!! I updated the first post. I also leave the link below:
https://gist.github.com/danielaDESM/1c4a77a86bb902cf82a0416742849ddd

**Comment by maxim-belkin** [comment] 2018-11-19 20:01
Great. Let's make small steps and start by fixing errors reported by `brew doctor`:
```
sudo mkdir -p /home/daniela/.linuxbrew/{etc,include,lib,opt,sbin,share,var/homebrew/linked,Cellar}
sudo chown -R $(whoami) /home/daniela/.linuxbrew/{etc,include,lib,opt,sbin,share,var/homebrew/linked,Cellar}
```
Once that is done, execute `brew doctor` and copy the results here

**Comment by danielaDESM** [comment] 2018-11-19 20:03
After crating the directories and changing the permissions and running again brew doctor:

daniela@daniela-XPS-8910:~/.linuxbrew$ brew doctor
Your system is ready to brew.

**Comment by maxim-belkin** [comment] 2018-11-19 20:05
OK, let's now do:
```
brew install --only-dependencies llvm@4
```

**Comment by danielaDESM** [comment] 2018-11-19 20:21
Sorry for the delay,

daniela@daniela-XPS-8910:~$ brew install --only-dependencies llvm@4
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
tinyxml2

All dependencies for llvm@4 are satisfied.

**Comment by danielaDESM** [comment] 2018-11-19 20:34
I got an error:
https://gist.github.com/eb53faa375440d68accaa006e39e09eb

**Comment by maxim-belkin** [comment] 2018-11-19 21:07
Weird. Could you please execute the following sequence of commands:
```sh
sed -i '/ENV.libcxx/a \ \ \ \ ENV.cxx11' $(brew --repo linuxbrew/core)/Formula/llvm@4.rb
export HOMEBREW_NO_AUTO_UPDATE=1
brew install --verbose llvm@4
```

**Comment by danielaDESM** [comment] 2018-11-19 21:13
It did not work :s

https://gist.github.com/danielaDESM/170e6edfda16115b740f9086c07fd8c6

**Comment by danielaDESM** [comment] 2018-11-19 21:39
Thanks a lot again

**Comment by maxim-belkin** [comment] 2018-11-19 22:35
I'm trying `DLLVM_ENABLE_LIBCXX=OFF`. I don't think `DCLANG_DEFAULT_CXX_STDLIB` has any effect for `gcc`

**Comment by maxim-belkin** [comment] 2018-11-19 22:35
In fact, I concur with @xu-cheng here: https://github.com/Linuxbrew/homebrew-core/pull/9146/files#r214277682

**Comment by iMichka** [comment] 2018-11-21 11:41
Let's try to revive the llvm 4 build: #10389

Regarding the comment from @xu-cheng : let's try first to get a clean `libstdc++` build. I do not care so much about `libc++` on Linux. I think that upstream (homebrew) removed the options and is just building `libc++` on mac. If somebody really needs this I would be willing to accept pull requests that align all the llvm formulae so that they all propose this option.

**Comment by danielaDESM** [comment] 2018-11-21 13:11
Thanks a lot to both.

**Comment by thoughton** [comment] 2018-12-24 13:32
Is this the same issue caused by the following error?
```
llvm-4.0.1.src/projects/libcxx/include/__locale:39:22: fatal error: xlocale.h: No such file or directory
```
Apparently `xlocale.h` was removed in `glibc 2.26` (https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27).
My `Ubuntu 18.04 LTS` system has version `2.27` and therefore no longer has the required header. (And I can't install Linuxbrew's earlier version of course due to compatibility issues.)

**Comment by thoughton** [comment] 2019-03-18 19:23
Please don't close this. Still fails to `reinstall` for me due to the `xlocale.h` error I mentioned above (https://github.com/Homebrew/linuxbrew-core/issues/10371#issuecomment-449734835).

**Comment by Char-Aznable** [comment] 2019-04-03 00:20
Same error here as the OP

**Comment by Char-Aznable** [comment] 2019-04-05 18:36
I have got a fix. Basically you need to remove all the libcxx stuff out of the way and change some cmake option when building the compiler-rt library

**Comment by maxim-belkin** [comment] 2019-04-05 19:10
Great to hear that! Would you like to submit a PR?

**Comment by Char-Aznable** [comment] 2019-04-08 23:55
See PR #12486

**Comment by thoughton** [comment] 2019-05-02 16:42
Not stale.

**Comment by thoughton** [comment] 2019-05-24 20:29
Not stale...

**Comment by issyl0** [comment] 2019-06-13 07:04
I’ve added the in-progress label to stop the stale bot posting for the fifth time! I’ll also try and revive the closed PRs around this and get it working, as it still seems to be a problem.

**Comment by chenzhekl** [comment] 2019-08-11 16:47
It seems no PRs are merged at the end and the broken `llvm@4` still breaks packages that depend on it (e.g., Embree). Hope someone can help fix it...

**Comment by iMichka** [comment] 2019-11-16 13:51
`pcl` does not depend on `llvm@4` anymore. A bottle has been built for it.

`llvm@4` has been deleted.

**Closed by iMichka** 2019-11-16 13:51 UTC
Labels: bug
