### ISSUE TITLE
can't brew install gitversion (actually dotnet) on ubuntu 

### ISSUE THREAD

**Issue by carnicer** [Homebrew/linuxbrew-core#22063] opened 2021-01-08 14:20 UTC
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install gitversion with brew, with command `brew install gitversion` as recommended by the gitversion web page: https://gitversion.net/docs/usage/command-line

It fails when brew tries to install a dependency (dotnet).

## What happened (include command output)

On a first attempt, the `brew install command` managed to install most dependencies, including `expat` and several others. It always fails when trying to install the `dotnet` dependency.

If I try to install the `dotnet` package alone, I get the same error.

When trying to run `brew gist-logs dotnet` I get an error about a token that needs to be set. If I set it with a github token I also get a _not found_ error.

<details>
  <summary>Command output</summary>
  <pre>
gonmarco@npdu472:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18
gonmarco@npdu472:~$ brew install gitversion
==> Cloning https://github.com/dotnet/source-build.git
Updating /home/gonmarco/.cache/Homebrew/dotnet--git
==> Checking out tag v3.1.110-SDK
HEAD is now at 2b1abb2 Merge pull request #1832 from dagood/3.1.110
HEAD is now at 2b1abb2 Merge pull request #1832 from dagood/3.1.110
==> Downloading https://github.com/GitTools/GitVersion/archive/5.6.1.tar.gz
Already downloaded: /home/gonmarco/.cache/Homebrew/downloads/6965e072a813ced305d9ad0369452265cc92d97f51ad3b382552ed20deff6f1e--GitVersion-5.6.1.tar.gz
==> Installing dependencies for gitversion: dotnet
==> Installing gitversion dependency: dotnet
==> ./build.sh /p:DownloadSourceBuildReferencePackagesTimeoutSeconds=N/A /p:DownloadSourceBuiltArtifactsTimeoutSeconds=N/A
Last 15 lines from /home/gonmarco/.cache/Homebrew/Logs/dotnet/01.build.sh:
     at Microsoft.DotNet.Darc.Operations.CloneOperation.HandleMasterCopyAndCreateGitDir(RemoteFactory remoteFactory, String repoUrl, String masterGitRepoPath, String masterRepoGitDirPath, String gitDirRedirect, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 291
     at Microsoft.DotNet.Darc.Operations.CloneOperation.HandleMasterCopyWithGitDirPath(RemoteFactory remoteFactory, String repoUrl, String masterGitRepoPath, String masterRepoGitDirPath, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 279
     at Microsoft.DotNet.Darc.Operations.CloneOperation.HandleMasterCopy(RemoteFactory remoteFactory, String repoUrl, String masterGitRepoPath, String masterRepoGitDirPath, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 232
     at Microsoft.DotNet.Darc.Operations.CloneOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 109
/tmp/dotnet-20210108-775826-1asavs6/tools-local/init-build.proj(204,5): error MSB3073: The command "/tmp/dotnet-20210108-775826-1asavs6/.dotnet/dotnet /tmp/dotnet-20210108-775826-1asavs6/.dotnet/tools/.store/microsoft.dotnet.darc/1.1.0-beta.19568.2/microsoft.dotnet.darc/1.1.0-beta.19568.2/tools/netcoreapp3.0/any/Microsoft.DotNet.Darc.dll clone  --git-dir-folder /tmp/dotnet-20210108-775826-1asavs6/.git/modules/src/ --include-toolset --ignore-repos ";https://dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/devdiv/DevDiv/_git/DotNet-Trusted;https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted;https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://github.com/dotnet/source-build-reference-packages" --debug --azdev-pat bogus --github-pat bogus --depth 0 --repos-folder /tmp/dotnet-20210108-775826-1asavs6/artifacts/src/" exited with code 42.

Build FAILED.

/tmp/dotnet-20210108-775826-1asavs6/packages/restored/microsoft.dotnet.arcade.sdk/1.0.0-beta.19359.6/tools/ProjectLayout.props(8,3): warning MSB4011: "/tmp/dotnet-20210108-775826-1asavs6/packages/restored/microsoft.dotnet.arcade.sdk/1.0.0-beta.19359.6/tools/RepoLayout.props" cannot be imported again. It was already imported at "/tmp/dotnet-20210108-775826-1asavs6/packages/restored/microsoft.dotnet.arcade.sdk/1.0.0-beta.19359.6/tools/Build.proj (52,3)". This is most likely a build authoring error. This subsequent import will be ignored.
/tmp/dotnet-20210108-775826-1asavs6/tools-local/init-build.proj(204,5): error MSB3073: The command "/tmp/dotnet-20210108-775826-1asavs6/.dotnet/dotnet /tmp/dotnet-20210108-775826-1asavs6/.dotnet/tools/.store/microsoft.dotnet.darc/1.1.0-beta.19568.2/microsoft.dotnet.darc/1.1.0-beta.19568.2/tools/netcoreapp3.0/any/Microsoft.DotNet.Darc.dll clone  --git-dir-folder /tmp/dotnet-20210108-775826-1asavs6/.git/modules/src/ --include-toolset --ignore-repos ";https://dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/devdiv/DevDiv/_git/DotNet-Trusted;https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted;https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://github.com/dotnet/source-build-reference-packages" --debug --azdev-pat bogus --github-pat bogus --depth 0 --repos-folder /tmp/dotnet-20210108-775826-1asavs6/artifacts/src/" exited with code 42.
    1 Warning(s)
    1 Error(s)

Time Elapsed 00:02:35.35
Build failed (exit code '1').

READ THIS: https://docs.brew.sh/Troubleshooting

gonmarco@npdu472:~$
gonmarco@npdu472:~$ export HOMEBREW_GITHUB_API_TOKEN=1fdbbd... # token deleted here
gonmarco@npdu472:~$ brew gist-logs dotnet
Error: Not Found
gonmarco@npdu472:~$

  </pre>
</details>

## What you expected to happen

I was expecting that the gitversion package and its dependencies would be installed successfully.

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install gitversion
brew install dotnet #this gives the same error
```

**Comment by danielnachun** [comment] 2021-01-19 19:51
I see that the `dotnet` formula has not yet been bottled on Linux, which often means it hasn't been tested on it.  When I tried to build it, I had an interesting result.  At first it failed very early with an error that seemed to be happening due to running out of RAM.  I requested more RAM from SLURM and then I made it much further in the build process, until failing with this error:

```
CMake Error at /tmp/dotnet-20210119-71527-sjmsge/artifacts/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/eng/native/functions.cmake:105 (message):
   Cannot find libunwind.  Try installing libunwind8-dev or libunwind-devel.
Call Stack (most recent call first):
   src/pal/src/CMakeLists.txt:20 (find_unwind_libs)
```

This seems to be caused by a problem with `clang` not being able to find `libunwind`, which is part of `llvm` but stores its libraries in subfolder of the main `llvm` cellar.  I will try a couple of things to see if I can get it to find the library, but if anyone has encountered this issue using brewed `clang` before let me know if you have ideas.

Once we can get this to build, the good news is that the cellar is marked as `:any` so nobody should have to build this from source, even if they are not using `/home/linuxbrew/.linuxbrew` as their install location.  We just need to get it build correctly in CI and then everyone will be able to download it precompiled.

**Comment by danielnachun** [comment] 2021-02-02 23:26
After digging into this a lot more, I think I was mistaken about `libunwind`.  There is a version that ships with LLVM, but there is also a version that ships with macOS, and that seems to be what `dotnet` is using on that platform.  On Linux, the libunwind we need is from here: https://github.com/libunwind/libunwind, and that appears to be Linux-only.  Arch Linux, for example, builds `dotnet` with that version of `libunwind` as a dependency (that's how I originally discovered this).  

I think we will need to make Linux-only formula for `libunwind`.  @iMichka until we merge linuxbrew/core into homebrew/core, where should we add new Linux-only formula?  I know there is still discussion about handling Linux CI in homebrew/core, let me know what makes the most sense.

**Comment by iMichka** [comment] 2021-02-03 06:40
You can open a PR here to test the build. Once it is OK you can then open the PR in homebrew-core to get it merged there. We do have linux-only CI in homebrew-core, you need to add this formula to the `.github/workflows/tests-linux.yml` file.

**Comment by lexicol** [comment] 2021-03-11 03:18
Got a bit further with `libunwind` formula, and this is the new error:

https://github.com/Homebrew/linuxbrew-core/runs/2082870203?check_suite_focus=true#step:7:181

```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.TextInfo..cctor()
   at System.String.ToLowerInvariant()
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.GetEnvironmentVariableAsBool(System.String, Boolean)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(System.String[], Microsoft.DotNet.Cli.Telemetry.ITelemetry)
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
```

This error appears even though `dotnet` has `depends_on "icu4c"`

**Comment by MikeMcQuaid** [comment] 2021-08-17 10:58
Closing, sorry. If this issue is still relevant: please reopen on homebrew-core.

**Closed by MikeMcQuaid** 2021-08-17 10:58 UTC
