### ISSUE TITLE
qt installation error

### ISSUE THREAD

**Issue by water-vapor** [Homebrew/linuxbrew-core#24241] opened 2021-08-12 03:18 UTC
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.6-100-gcd900ef
ORIGIN: https://github.com/Homebrew/brew
HEAD: cd900ef71eeecb621faba88aabc641fe93325fe6
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 94a00f4131be6f53bc6d4e8376d95fc52857ee86
Core tap last commit: 7 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 20-core 64-bit unknown_0x6_0xa5
Clang: 12.0.1 build (parse error)
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 5.4.0-77-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.5 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.5.0
/usr/bin/ruby: 2.5.1
glibc: N/A
gcc@5: 5.5.0_7
xorg: N/A

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install qt`

### What happened (include all command output)?

Build failure
```
==> Downloading https://download.qt.io/official_releases/qt/6.1/6.1.2/single/qt-
Already downloaded: /home/vapor/.cache/Homebrew/downloads/269b760a63df089bb40a7f27dcd64e2ba7e3c9a64d0dfdd40c31c2935f2d3e5d--qt-everywhere-src-6.1.2.tar.xz
==> ./configure -release -prefix /home/linuxbrew/.linuxbrew -extprefix /home/lin
Last 15 lines from /home/vapor/.cache/Homebrew/Logs/qt/01.configure:
-DFEATURE_pkg_config=ON
-DFEATURE_qt3d_system_assimp=ON
-DTEST_assimp=ON

+ cd qtbase
+ /tmp/qt-20210811-31129-npl6uy/qt-everywhere-src-6.1.2/qtbase/configure -top-level -release -prefix /home/linuxbrew/.linuxbrew -extprefix /home/linuxbrew/.linuxbrew/Cellar/qt/6.1.2 -sysroot  -archdatadir share/qt -datadir share/qt -examplesdir share/qt/examples -testsdir share/qt/tests -libproxy -no-feature-relocatable -system-sqlite -no-sql-mysql -no-sql-odbc -no-sql-psql -- -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET= -DCMAKE_FIND_FRAMEWORK=FIRST -DINSTALL_MKSPECSDIR=share/qt/mkspecs -DFEATURE_pkg_config=ON -DFEATURE_qt3d_system_assimp=ON -DTEST_assimp=ON
CMake Error at qtbase/cmake/QtProcessConfigureArgs.cmake:232 (message):
  No value supplied to command line options 'sysroot'.
Call Stack (most recent call first):
  qtbase/cmake/QtProcessConfigureArgs.cmake:333 (qtConfAddError)
  qtbase/cmake/QtProcessConfigureArgs.cmake:421:EVAL:1 (qt_commandline_string)
  qtbase/cmake/QtProcessConfigureArgs.cmake:421 (cmake_language)
  qtbase/cmake/QtProcessConfigureArgs.cmake:542 (qt_call_function)



READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Installing qt@5 faild https://github.com/Homebrew/linuxbrew-core/issues/23293
qt: Fix build for Linux https://github.com/Homebrew/linuxbrew-core/pull/22412
qt@5: revision bump for icu4c https://github.com/Homebrew/linuxbrew-core/pull/23174
```

### What did you expect to happen?

Build success.
The `qt.rb` file seems to be macOS specific. The complaining line feeds macOS SDK path into that "sysroot" option, which is not available on linux. The same issue is reproduced on two machines with Ubuntu 18.04 and 20.04

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install qt`
```

**Comment by iMichka** [comment] 2021-08-12 08:35
Duplicate of #22412

**Closed by iMichka** 2021-08-12 08:35 UTC
Labels: bug
