### ISSUE TITLE
Wrong commit hash in minikube formulae

### ISSUE THREAD

**Issue by giang-nghg** [Homebrew/linuxbrew-core#21096] opened 2020-09-11 05:42 UTC
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install `minikube`

## What happened (include command output)

brew install minikube

<details>
  <summary>Command output</summary>
  <pre>

  ==> Downloading https://linuxbrew.bintray.com/bottles/go-1.15.1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/giang/.cache/Homebrew/downloads/62c4de0bae6ee0e8116dd04fd25b1609038746fb9324b761e22b5dff85c11e14--go-1.15.1.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/go-bindata-3.21.0.x86_64_linux.bottle.tar.gz
Already downloaded: /home/giang/.cache/Homebrew/downloads/55706724bcb823f0fb9fa2de4b02eada4fe361a0cd0cd57a5ae13172984cb57f--go-bindata-3.21.0.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/kubernetes-cli-1.19.1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/giang/.cache/Homebrew/downloads/0cea33585408cbae2b1b153540064a76cd77a030af8e454475a1d35c0a945d20--kubernetes-cli-1.19.1.x86_64_linux.bottle.tar.gz
==> Cloning https://github.com/kubernetes/minikube.git
Updating /home/giang/.cache/Homebrew/minikube--git
==> Checking out tag v1.13.0
HEAD is now at 0c5e9de Merge pull request #9182 from sharifelgamal/fix-release-make
HEAD is now at 0c5e9de Merge pull request #9182 from sharifelgamal/fix-release-make
Entering 'site/themes/docsy'
Synchronizing submodule url for 'assets/vendor/Font-Awesome'
Synchronizing submodule url for 'assets/vendor/bootstrap'
Entering 'site/themes/docsy/assets/vendor/Font-Awesome'
Entering 'site/themes/docsy/assets/vendor/bootstrap'
/home/giang/.cache/Homebrew/minikube--git/site/themes/docsy
/home/giang/.cache/Homebrew/minikube--git/site/themes/docsy/assets/vendor/Font-Awesome
/home/giang/.cache/Homebrew/minikube--git/site/themes/docsy/assets/vendor/bootstrap
Error: v1.13.0 tag should be eeb05350f8ba6ff3a12791fcce350c131cb2ff44
but is actually 0c5e9de4ca6f9c55147ae7f90af97eff5befef5f

  </pre>
</details>

brew gist-logs minikube

<details>
  <summary>Command output</summary>
  <pre>

  Error: No logs.

  </pre>
</details>

brew config

<details>
  <summary>Command output</summary>
  <pre>

  HOMEBREW_VERSION: 2.5.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ec8266697b2c9838cef86f8f97b5f392d0f926d
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 4327d74d5ca71266f8ff7f3dc7a45fb13d6f2043
Core tap last commit: 7 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.15.0-1096-oem x86_64 GNU/Linux
OS: Ubuntu 18.04 LTS (beaver-three-eyed-raven X92) (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.5.0
/usr/bin/ruby: N/A
glibc: N/A
gcc: N/A
xorg: N/A

  </pre>
</details>

brew doctor

<details>
  <summary>Command output</summary>
  <pre>

  Your system is ready to brew.

  </pre>
</details>

## What you expected to happen

`minikube` should be installed successfully

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install minikube`

**Comment by jonchang** [comment] 2020-09-11 05:47
Duplicate of https://github.com/Homebrew/homebrew-core/issues/60746

**Closed by jonchang** 2020-09-11 05:47 UTC
